keypoints_list = [
    "NOSE",
    "LEFT_EYE",
    "RIGHT_EYE",
    "LEFT_EAR",
    "RIGHT_EAR",
    "LEFT_SHOULDER",
    "RIGHT_SHOULDER",
    "LEFT_ELBOW",
    "RIGHT_ELBOW",
    "LEFT_WRIST",
    "RIGHT_WRIST",
    "LEFT_GROIN",
    "RIGHT_GROIN",
    "LEFT_KNEE",
    "RIGHT_KNEE",
    "LEFT_ANKLE",
    "RIGHT_ANKLE",
    "LEFT_BIG_TOE",
    "LEFT_LITTLE_TOE",
    "LEFT_HEEL",
    "RIGHT_BIG_TOE",
    "RIGHT_LITTLE_TOE",
    "RIGHT_HEEL",
]

keypoints_info = {
    "NOSE": "鼻",
    "LEFT_EYE": "左目",
    "RIGHT_EYE": "右目",
    "LEFT_EAR": "左耳",
    "RIGHT_EAR": "右耳",
    "LEFT_SHOULDER": "左肩",
    "RIGHT_SHOULDER": "右肩",
    "LEFT_ELBOW": "左肘",
    "RIGHT_ELBOW": "右肘",
    "LEFT_WRIST": "左手首",
    "RIGHT_WRIST": "右手首",
    "LEFT_GROIN": "左鼠径部",
    "RIGHT_GROIN": "右鼠径部",
    "LEFT_KNEE": "左膝",
    "RIGHT_KNEE": "右膝",
    "LEFT_ANKLE": "左足首",
    "RIGHT_ANKLE": "右足首",
    "LEFT_BIG_TOE": "左親指",
    "LEFT_LITTLE_TOE": "左小指",
    "LEFT_HEEL": "左踵",
    "RIGHT_BIG_TOE": "右親指",
    "RIGHT_LITTLE_TOE": "右小指",
    "RIGHT_HEEL": "右踵",
}
